### ISSUE TITLE
problem when updating to version 1.4.0.5 or 1.4.0.6 from 1.4.0.3.Beta1

### ISSUE THREAD

**Issue by deviantus** [jprante/elasticsearch-jdbc#429]
Hi, we have 3 node es cluster which is running es v1.4.2 and jdbc river 1.4.0.3.beta1. I tried to update 1.4.0.5 today. I follow these steps.
- shutdown the node
- remove old plugin
- install 1.4.0.5
- started node.
- node joined cluster.

but node did not do shard allocation. when looked at log I saw below lines repeating. Could it be bug?

```
[2014-12-30 16:26:54,919][DEBUG][discovery.zen            ] [node1] filtered ping responses: (filter_client[true], filter_data[false])
    --> ping_response{node [[node3][IPkqBGxlSu2eqwtr1FVdQA][SRV03][inet[/xxx.xxx.xx.191:9300]]], id[653], master [[node3][IPkqBGxlSu2eqwtr1FVdQA][SRV03][inet[/xxx.xxx.xx.191:9300]]], hasJoinedOnce [true], cluster_name[dnr]}
    --> ping_response{node [[node2][QBLhSjpXQFStmHQa15PoCw][SRV02][inet[/xxx.xxx.xx.190:9300]]], id[635], master [[node3][IPkqBGxlSu2eqwtr1FVdQA][SRV03][inet[/xxx.xxx.xx.191:9300]]], hasJoinedOnce [true], cluster_name[dnr]}
[2014-12-30 16:26:54,919][DEBUG][transport.netty          ] [node1] connected to node [[node3][IPkqBGxlSu2eqwtr1FVdQA][SRV03][inet[/xxx.xxx.xx.191:9300]]]
[2014-12-30 16:26:55,013][DEBUG][cluster.service          ] [node1] processing [finalize_join ([node3][IPkqBGxlSu2eqwtr1FVdQA][SRV03][inet[/xxx.xxx.xx.191:9300]])]: execute
[2014-12-30 16:26:55,013][DEBUG][discovery.zen            ] [node1] no master node is set, despite of join request completing. retrying pings.
[2014-12-30 16:26:55,013][DEBUG][cluster.service          ] [node1] processing [finalize_join ([node3][IPkqBGxlSu2eqwtr1FVdQA][SRV03][inet[/xxx.xxx.xx.191:9300]])]: no change in cluster_state
[2014-12-30 16:26:55,013][DEBUG][transport.netty          ] [node1] connected to node [[#zen_unicast_2#][SRV01][inet[SRV02/xxx.xxx.xx.190:9300]]]
[2014-12-30 16:26:55,013][DEBUG][transport.netty          ] [node1] connected to node [[#zen_unicast_3#][SRV01][inet[SRV03/xxx.xxx.xx.191:9300]]]
[2014-12-30 16:26:58,044][DEBUG][transport.netty          ] [node1] disconnecting from [[#zen_unicast_2#][SRV01][inet[SRV02/xxx.xxx.xx.190:9300]]] due to explicit disconnect call
[2014-12-30 16:26:58,044][DEBUG][transport.netty          ] [node1] disconnecting from [[#zen_unicast_3#][SRV01][inet[SRV03/xxx.xxx.xx.191:9300]]] due to explicit disconnect call

```

I tried same with 1.4.0.6 nothing changed and I rolled back to 1.4.0.3.Beta1

**Comment by deviantus** [comment]
You right, but this happens when I updated the plugin. I didn't update plugin at the same on all nodes. is that can cause problem? Because when a updated plugin on a node and joined the cluster, there are rivers which created by old version of jdbc river. What is the best scenario of updating plugin on running cluster?

**Comment by ArtyomBaranovskiy** [comment]
The same for me (#439). Unfortunately, I still cannot update to 1.4.0.8.
